### ISSUE TITLE
not always initializing properly

### ISSUE THREAD

**Issue by almerv** [raphaelquast/beatstep#22]
I try to use this script but it's not always initializing properly because sometimes the encoders still send on channel 1 instead of 10,
and I don't see any errors in the Log file

**Comment by raphaelquast** [comment]
hey, sorry to hear that...   
since there's no error, can you answer some questions so that i can pinpoint the problem:

- do you use the most recent version of the scipt?
- did you plug in BeatStep before launching Ableton?
  ...to ensure proper initialization, you must **plug in the controller after launching ableton**!

**Comment by almerv** [comment]
thanks it works if i plug in the controller after launching ableton
