### ISSUE TITLE
implement button to change "pad velocity curve"

### ISSUE THREAD

**Issue by almerv** [raphaelquast/beatstep#28]
The midi note velocity is always 127 instead of sensitive to velocity

**Comment by raphaelquast** [comment]
hey, thanks for the comment!

at the moment the pad velocity curve (linear, exponential, logarithmic or "always 127") is not explicitly set by the script, so the initial setting you apply via the "midi control center" should be maintained...

- It would be possible to implement an option to change the assigned velocity curve via the script.
   one of the unassigned buttons in the "song-control" layer could be used to toggle the available options....  
   e.g. something like:
   - blue light: linear
   - magenta light: exponential
   - red light: logarithmic
   - light off: always 127

Do you think something like this would be helpful ?

**Comment by almerv** [comment]
yes I think that would be a great option to have.
I'm still having issues with initialization if i turn on the beatstep after starting ableton,
So I have to deselect everything under 'Control Surface' in the Ableton MIDI settings,
and then turn on the BeatStep. 
But then the default BeatStep controller script gets activated and I think this sets the velocity to full. 
So it would be very helpful to be able to change the velocity setting without using the MCC

**Comment by raphaelquast** [comment]
OK, I'll have a look at the velocity-curve implementation!
It'll come with the next release (v1.5) together with the other changes (see here: #30)

-> if you have further suggestions, let me know! (I'm still trying to get the best out of this controler 😄 )

------------
concerning the initialization, I just did some testing (since there's absolutely no docmentation on all of this...)
and I've found that you might have problems with the order in which ableton selects scripts if there is more than one suitable available...

you might try one of the following to ensure that the BeatStep_Q script is found first
- rename the initial `BeatStep` folder to `_BeatStep`    
  (it seems folders with an underscore are not selected automatically)
- rename `BeatStep_Q` to `BBeatstep_Q`
   (or any other change in the folder-name that does the job... )

**Comment by raphaelquast** [comment]
@almerv I've successfully implemented the feature and it does it's job nicely 🥳  
I'll try to release a new version (v1.5) that includes all pending changes in the next few days!
(if you want it right away, it's already in the dev-branch)

**Comment by raphaelquast** [comment]
@almerv I've released [BeatStep_Q v1.5](https://github.com/raphaelquast/beatstep/releases/tag/v1.5) now!
if you find the time, could you try it out to see if the new feature is working as expected?

**Comment by almerv** [comment]
yes it works as expected

**Comment by raphaelquast** [comment]
great 😄 then I'll close this one for now!
